import { GetServerSideProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ repositories }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meus repos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Meus Repos
        </h1>
        <ul>
          {
            repositories.map((item)=> {
              return (<li key={item.name}>{item.name}</li>)
            })
          }
        </ul>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async ()=> {
  const response = await fetch(`https://api.github.com/users/cgama-dev/repos`)
  
  const data = await response.json()
  return {
    props: {
      repositories: data
    }
  }
}